### ISSUE TITLE
Can't install latest devel via homebrew

### ISSUE THREAD

**Issue by erebuscv** [chrmoritz/homebrew-starcheat#3]
attempting to brew install the latest dev version for mac is throwing this error

`Last 15 lines from /Users/erebus/Library/Logs/Homebrew/starcheat/02.python:
2019-09-29 15:06:59 -0500

python
-s
/private/tmp/starcheat--homebrew-virtualenv-20190929-22557-1ox5vo8/target/bin/virtualenv
-p
python
/usr/local/Cellar/starcheat/1.0/libexec

python: can't open file '/private/tmp/starcheat--homebrew-virtualenv-20190929-22557-1ox5vo8/target/bin/virtualenv': [Errno 2] No such file or directory

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/chrmoritz/homebrew-starcheat/issues`

**Comment by chrmoritz** [comment]
Thanks for reporting this!

Looks like there are some issue with installing `Pillow` (our image library) with recent macOS releases. So I guess it is better to start recommending to install their official binaries with `pip` instead of failing to try to build it from source.

Should be fixed now. Try to run
```bash
brew update && brew install starcheat --devel && pip3 install --upgrade Pillow
```
